gluon-lang/gluon

src/repl.rs
std/repl.glu

- Use `"> "` as repl prompt
- Add basic help message at startup
- Skips parsing if an empty line is entered
- Adds previous expressions to linenoise history so that you can get back to them using the arrow keys
- Quit repl on ^C and ^D

Repl UX improvements

---

Cargo.toml
src/main.rs
src/repl.rs
std/repl.glu

Rustyline is a pure rust implementation of linenoise with some additional features which will make it possible to add completion to the repl.
The windows support in Rustyline is currently only partial (history support and modifier keys are not yet working). I will likely add in completion support as well before merging.

refactor: Replace linenoise with rustyline

---

base/src/types.rs
check/src/typecheck.rs
check/tests/typecheck.rs
std/prelude.glu
std/state.glu

Without instantiating the type signature all uses of the function arguments would instantiate the argument's type with fresh variables on every use which easily masked the problem by allowing wrongly typed code to pass.

fix(check): Don't bind uninstantiated type signatures to arguments

---

Cargo.toml
c-api/Cargo.toml
check/Cargo.toml
parser/Cargo.toml
vm/Cargo.toml

I find the map version of specifying dependencies easier to scan and update. Not sure if you agree!
I've also added a workspace so that if you do a build in a sub-directory it will reuse the root target directory.
Rustyline has been pegged to a specific git revision so as to ensure repeatable builds.

Update dependencies and add workspace field

---

base/src/instantiate.rs
benches/check.rs
check/src/substitution.rs
check/src/typecheck.rs

Gives a ~65% speedup on the typecheck_prelude benchmark

perf(check): Avoid recreating identical App instances in unroll_app

---

vm/src/compiler.rs
vm/src/thread.rs
vm/src/types.rs

In addition to adding doc comments I also removed the unused `GetIndex` instruction and made the two argument variants into struct variants to avoid ambiguity.

docs: Document the Instruction enum

---

base/src/types.rs
check/src/completion.rs
check/src/kindcheck.rs
check/src/rename.rs
check/src/typecheck.rs
check/src/unify.rs
check/src/unify_type.rs

Simplifies a few parts of the unification and runs clippy on the check crate. Wanted to use quick-error on the error types as well but unfortunately quick-error does not support parameterized errors.

Refactor parts of the check crate

---

src/lib.rs
vm/src/macros.rs

@brendanzab 
I tried to do this as was said in the issue. I've exported a GLUON_PATH variable and it appears to get read while the vm is created. 
Feel free to completely reject this code if it's not up to snuff, as I said before I'm just a beginner with Rust.
In the interest of adding the path without any explicit conditionals, I added a method `insert_and_get` to `vm/src/macros` so that the function calls could be chained. If no path is found, it should just grab the current directory. 
Rebased off of master just prior.

read GLUON_PATH from env var and add to new_vm

---

base/src/types.rs
src/repl.rs
vm/src/api.rs
vm/src/vm.rs

Re-submitted PR of #73 since I apparently closed that instead of merging

Fix a few error cases when using `:i`, `:k` and `:t` from the repl

---

check/tests/completion.rs
check/tests/fail.rs
check/tests/metadata.rs
check/tests/pass.rs
check/tests/stack_overflow.rs
check/tests/support/mod.rs

- Moved common functions to a support module, as is common in most Rust projects.
- Prefer qualifying functions by module, and remove glob imports.
- Assign most expected values to `expected` binding before asserting equality.

Clean up tests for check module

---

TUTORIAL.md
c-api/src/lib.rs
src/io.rs
src/lib.rs
tests/api.rs
tests/io.rs
tests/parallel.rs
tests/tutorial.rs
tests/vm.rs

Closes #83 
Note that this changes `run_expr` and `run_io_expr` to return the inferred type along with the value. Not sure if that's ok :/

Print type along with value when when evaluating in the repl

---

base/src/types.rs
check/src/kindcheck.rs
check/src/substitution.rs
check/src/typecheck.rs
check/src/unify.rs
check/src/unify_type.rs
check/tests/support/mod.rs

This PR should ensure that incredibly long generic names like `a00000001` does not occur anymore. It also includes some additional cleanup to the `check` crate and performance improvement when it comes to generalizing.
Closes #74

feat(check): Generate generic variable names less naively

---

base/src/ast.rs
base/src/types.rs
check/src/completion.rs
check/src/lib.rs
check/src/rename.rs
check/src/typecheck.rs
check/src/unify_type.rs
check/tests/completion.rs
check/tests/pass.rs
check/tests/support/mod.rs
vm/src/compiler.rs

Done as part of working towards #50.
`env_type_of` could probably be renamed, but I think it's ok for now.
I also removed some trait object indirection, and some unused impls for the env traits.

Remove Typed::type_of function

---

base/src/ast.rs
base/src/symbol.rs
base/src/types.rs
base/tests/types.rs
c-api/src/lib.rs
check/src/typecheck.rs
check/src/unify_type.rs
parser/src/lib.rs
parser/tests/basic.rs
src/io.rs
src/lib.rs
src/repl.rs
tests/api.rs
tests/compile-fail/getable-reference.rs
tests/compile-fail/store-ref.rs
tests/vm.rs
vm/src/api.rs
vm/src/channel.rs
vm/src/compiler.rs
vm/src/interner.rs
vm/src/lazy.rs
vm/src/primitives.rs
vm/src/reference.rs
vm/src/stack.rs
vm/src/thread.rs
vm/src/types.rs
vm/src/value.rs
vm/src/vm.rs

Fixes #90 
refactored type identifiers are
```Rust
ASTType
VMIndex
VMInt
VMType
VMError
VMTag
VMFunction
VMResult
VMEnv
GlobalVMState
```

refactor: Camelise type identifiers with acronyms/initialisms

---

src/io.rs
src/repl.rs
test-nightly.sh
tests/api.rs
tests/compile-fail/getable-reference.rs
tests/compile-fail/store-ref.rs
tests/compiletest.rs
vm/src/api.rs
vm/src/channel.rs
vm/src/lazy.rs
vm/src/reference.rs
vm/src/value.rs

By removing the blanket implementation on the `value::Userdata` trait. types can instead opt-in to use the `Userdata` representation in the vm. This means users only need to write `ìmpl Userdata for MyType { }` to allow them to define functions in gluon which create new values of `MyType` (`fn make_my_type(_: ()) -> MyType` works)

refactor(vm): Remove the need for the api::Userdata wrapper

---

CONTRIBUTING.md
Cargo.toml
test-nightly.sh

This will let nightly users to build directly in the root folder.

chore: Enable workspaces in cargo

---

.travis.yml
Cargo.toml
README.md
src/repl.rs
vm/src/thread.rs

This has the usual caveat that completing other modules will not work and they must be explicitly imported first
```
let prelude = import "std/prelude.glu"
prelude.n // Yields prelude.not, prelude.num_Int, etc
```
```
prelude. // Nothing
std.prelude. // Nothing
```

feat(repl): Add completion to the repl

---

.travis.yml

The regression in rust-lang/rust#35721 will most likely not be backported to beta until next week - see https://github.com/rust-lang/rust/pull/35733#issuecomment-241099928 - so it probably makes sense to disable it for now.
I also cherrypicked #120 because it would have caused a conflict.

Disable beta on CI builds

---

parser/Cargo.toml
parser/src/lexer.rs
parser/src/lib.rs
parser/tests/basic.rs

The strings are already allocated by the parser, so it is easier just to delay this until we hit the parser. This greatle simplifies the type signatures in the lexer, and will make it much easier to transition to LALRPOP. For efficiency's sake, we should eventually transition to using slices in the lexer though.

Delay string interning until parse time

---

check/src/completion.rs
check/tests/completion.rs
src/import.rs
src/lib.rs

Before the closest identifier to the left of the location would be completed which meant
```f#
test   abc
//   ^ completion here would complete `test` instead of listing local variables
```
This fix ensures that local variables are enumerated instead.

fix(completion): Give completion for local variables when pointing to whitespace

---

benches/function_call.rs
c-api/src/lib.rs
src/io.rs
src/lib.rs
test-nightly.sh
tests/vm.rs
vm/src/api.rs
vm/src/channel.rs
vm/src/lazy.rs
vm/src/primitives.rs
vm/src/stack.rs
vm/src/thread.rs

This gives a noticeable performance improvement for code which frequently enters and leaves the vm itself as only one mutex need to be locked. It does complicate some of the surrounding code slightly but this will be a necessary change regardless since the now added `Contex` type can be extended with additional fields which would otherwise involve adding more locks.
Before
```
test factorial                    ... bench:     249,725 ns/iter (+/- 12,150)
test factorial_tail_call          ... bench:     242,908 ns/iter (+/- 13,685)
test gluon_rust_boundary_overhead ... bench:     396,684 ns/iter (+/- 34,313)
```
After
```
test factorial                    ... bench:     128,571 ns/iter (+/- 7,537)
test factorial_tail_call          ... bench:     125,914 ns/iter (+/- 6,374)
test …
```

perf: Use a single mutex for both the stack and gc

---

parser/src/lib.rs

Due to the long compile times of the current parser a specialized version used by the rest of the crates is compiled into the parser crate itself letting the other crates remain unaffected.

fix(parser): Instantiate a specialized version of parse in the parser crate

---

.travis.yml
Cargo.toml
build.rs
c-api/Cargo.toml
test-nightly.sh
test-no-skeptic.sh
tests/skeptic-tests.rs

This solution feels a bit heavy handed but at least it seems like skeptic no longer fails on travis from the 5 or so times I reran it.
This also enables beta testing again on travis since the rustc fixes has been backported.
Fixes #149

chore: Only test using skeptic on stable when running in travis

---

check/tests/support/mod.rs
parser/Cargo.toml
parser/src/lexer.rs
parser/src/lib.rs
parser/tests/basic.rs
parser/tests/indentation.rs
parser/tests/stack_overflow.rs
src/lib.rs

This relies on an a branches of combine and combine-language that are not yet released (but will be tomorrow). It is also likely conflicts with #103, we can hold of merging this until after LALRPOP if you like @brendanzab, looks like it is getting pretty close(?).
```
<top>:Line: 1, Column: 7: Unexpected `Operator`
Expected `Equal`
let x <<
^~
Stacktrace:
```
Fixes #151

[WIP] Display line and column locations for parse errors

---

.travis.yml

Getting failures every single PR now so until skeptic can be made to work on travis I think we need to disable it completely.

chore: Disable skeptic tests on travis

---

base/src/ast.rs
base/src/instantiate.rs
base/src/types.rs
check/src/kindcheck.rs
check/src/rename.rs
check/src/typecheck.rs
check/tests/support/mod.rs
parser/src/lexer.rs
parser/tests/basic.rs
src/repl.rs
vm/src/api.rs
vm/src/compiler.rs
vm/src/types.rs
vm/src/value.rs
vm/src/vm.rs

This cleans up a bunch of `Option` juggling and makes things a bit easier to understand!

Move abstract types out of AliasData

---

base/src/types.rs
base/tests/types.rs
check/src/completion.rs
check/src/kindcheck.rs
check/src/rename.rs
check/src/typecheck.rs
check/src/unify_type.rs
check/tests/pass.rs
parser/src/lib.rs
parser/tests/basic.rs
vm/src/compiler.rs
vm/src/types.rs
vm/src/vm.rs

Like extensible records, you can't actually do much with these at the moment, but it _does_ simplify the internal representation somewhat.

Use rows for variant constructors

---

benches/function_call.rs
src/compiler_pipeline.rs
src/io.rs
tests/api.rs
tests/compile-fail/get-reference.rs
tests/compile-fail/getable-reference-str.rs
tests/compile-fail/getable-reference.rs
tests/compile-fail/store-ref.rs
tests/pass/deep_clone_userdata.glu
tests/tutorial.rs
vm/src/api.rs
vm/src/channel.rs
vm/src/lazy.rs
vm/src/primitives.rs
vm/src/reference.rs
vm/src/thread.rs
vm/src/value.rs
vm/src/vm.rs

So the issue in #193 was that a module would be loaded from a child thread which means the objects were allocated from that thread as well. After the child thread was destroyed the values allocated from that thread still existed in the global table being potentially referenced again. To fix this we deep clone any values stored in the global table into the `GlobalVmState` gc which ensures they live long enough.
Fixes #193

fix(vm): Only store generation-0 values in the globals table

---

base/src/ast.rs
base/src/error.rs
base/src/pos.rs
check/src/completion.rs
check/tests/completion.rs
check/tests/pass.rs
parser/src/lexer.rs
parser/src/lib.rs
parser/tests/basic.rs
src/lib.rs
tests/vm.rs
vm/src/thread.rs

This is an attempt of a less hacky alternative to #190. By tracking the source of an expression the completion requests can skip over expanded expressions (like the implicit prelude) and only search in the non expanded expressions.
This increases the size of `Span<BytePos>` by 50% which, being a frequently used type, is rather unfortunate. We could maybe do some trickery to reduce this but this could be done later if it is necessary.
(Supersedes)
Closes #190

fix: Track from where a part of the AST originated

---

.travis.yml

I think this should solve #194. The repl executable should be the only relevant file to upload

feat: Add the repl binary to github releases

---

tests/vm.rs
vm/src/compiler.rs

Ideally partially applied constructors should be compiled into an automatically generated lambda but until then we should at least not panic when encountering one.
Fixes #202

fix: Don't panic when compiling partially compiled constructors

---

build.rs

Caused by rust-lang/cargo#3368.
See https://github.com/rust-lang/cargo/issues/3368#issuecomment-265900350 for more information.

Fix build failure due to missing environment var

---

check/src/lib.rs
check/src/typecheck.rs
check/src/unify_type.rs
std/string.glu
tests/pass/string.glu
tests/safety.rs
tests/vm.rs
vm/Cargo.toml
vm/src/api.rs
vm/src/array.rs
vm/src/channel.rs
vm/src/gc.rs
vm/src/interner.rs
vm/src/lazy.rs
vm/src/lib.rs
vm/src/primitives.rs
vm/src/reference.rs
vm/src/thread.rs
vm/src/value.rs
vm/src/vm.rs

The bulk of these changes are to replace the use of `GcPtr<Str>` with a type backed by the normal array type. This makes it possible to convert `Array Byte` directly into `String` without copying any data.
Based on #235

feat(vm): Add a from_ut8 method for converting `Array Byte` into `String`

---

check/src/lib.rs
check/src/typecheck.rs
check/src/unify_type.rs
tests/vm.rs
vm/Cargo.toml
vm/src/api.rs
vm/src/lib.rs
vm/src/thread.rs

This means that aliases are resolved when retrieving bindings and
generic type parameters can be specialized.
Extracted from #226 and extended to work with specialized type parameters (i.e `id : a -> a` can be retrieved as `Int -> Int`)

fix(vm): Make get_global's type check act as a type signature check

---

check/src/lib.rs
check/src/typecheck.rs
check/src/unify_type.rs
tests/safety.rs
tests/vm.rs
vm/Cargo.toml
vm/src/api.rs
vm/src/channel.rs
vm/src/gc.rs
vm/src/lazy.rs
vm/src/lib.rs
vm/src/reference.rs
vm/src/thread.rs
vm/src/value.rs
vm/src/vm.rs

Plugs a memory safety hole which would be very simple for a user to introduce. See the added tests from a sketch of what would have been unsafe prior to this PR. This PR ensures that the owner of a `OpaqueValue` is taken into consideration when pushing it to a thread so that it will get copied if it is not possible to share it.
Builds on #234

fix(vm): Deep clone OpaqueValue when it is sent between disjoint threads

---

check/src/typecheck.rs
check/tests/fail.rs
check/tests/support/mod.rs
tests/vm.rs

Also fixes an issue with the implicit prelude which would cause a panic in source.rs

fix(check): Only mark the span of `let` and `type` expressions body

---

parser/src/token.rs
vm/src/value.rs

Hello, while playing with the REPL I noticed that it would panic when trying to parse a big integer:
```
$ ./target/release/repl -i
> 12345678901234567890
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: Overflow }', ../src/libcore/result.rs:837
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', ../src/libcore/result.rs:837
```
So I investigated a bit and found out that `numeric_literal` in `parser/src/token.rs` would `unwrap` the integers it tried to parse, causing the panic. So I've added a new `ErrorCode` in this module to represent integer parse errors. There's also an `unwrap` for floating point parsing, but I can't find a way to make it panic so I guess …

Prevent the REPL from panicking when parsing an overflowing integer

---

parser/src/grammar.lalrpop
parser/src/lib.rs
parser/src/token.rs
parser/tests/error_handling.rs
tests/vm.rs
vm/src/value.rs

Fixes the problem mentioned in #247 where tokenizer errors would not be propagated out from the parser

fix(parser): Return tokenizer errors from the parser

---

base/src/scoped_map.rs
tests/vm.rs
vm/src/compiler.rs

See compiler.rs:919-929. By using `Split` all fields in the value are pushed but when `Compiler::pop_pattern` is called to remove these variables it only removes the number of fields in the pattern (which may be fewer). To fix this I refactored the code a bit to use `ScopedMap` which is already used to do this kind of cleanup.
Extracted from #213, it has a few changes which aren't strictly necessary (new_stack_var taking a `&Compiler` argument) but is otherwise a pretty clean extraction.

fix(compiler): Pop the correct amount of variables in the compiler

---

parser/src/layout.rs
parser/tests/error_handling.rs

In the added test the lalrpop parser would enter error recovery and then repeatedly ask the lexer for tokens until a token that could succeed is found. Unfortunately due to the `,` token the layout algorithm would drop all contexts resulting in a default block to be added which again would be dropped (followed by the default block being added again etc.).
This is a kind of hack but I do believe that just returning the token is the best idea here since if it cannot be recoevered from then the parser will just drop it and request a new (real) token which has a better chance of succeding.

fix(parser): Don't loop forever from inserting default blocks

---

base/src/ast.rs
base/src/resolve.rs
base/src/types.rs
check/src/lib.rs
check/src/rename.rs
check/src/typecheck.rs
check/src/unify_type.rs
check/tests/pass.rs
check/tests/support/mod.rs
parser/src/grammar.lalrpop
parser/tests/basic.rs
parser/tests/support/mod.rs
src/repl.rs
vm/src/compiler.rs
vm/src/types.rs
vm/src/value.rs
vm/src/vm.rs

This is a bit of a weird one. The fundamental idea behind this commit is to make any 'alias' type always know the type it aliases. So for instance, if `Option a` is encountered we always know what the representation (`| None | Some a`) is. Before this commit this was not always the case as `Option a` could be `App(Ident("Option"), Generic("a"))` and not `App(Alias("Option"), Generic("a"))`.
However, due to Rust's ownership semantics preventing cyclic reference we need to be a bit clever. Each group of `type ... and ... in` is combined into the same type (`AliasData`) since these groups are the only places which types can be mutually recursive. Then when the aliased type (`| None | Option a`) is requested by calling `fn typ` we walk through the type and replace any occurances of …

fix(check): Don't leak `Type::Ident` outside of aliased types

---

CONTRIBUTING.md
README.md
TUTORIAL.md

Mostly commas and slight rewording in markdown files.
I also bumped the README Cargo.toml to 0.3 due to the changes in documentation of `import!`
I tried not to be too opinionated on wording as a first pass.

chore: Fix grammatical errors and touchup docs

---

src/io.rs
src/main.rs
std/repl.glu
vm/src/api.rs
vm/src/thread.rs

I think this should fix the missing output on osx, I changed `io.print` to not output a newline a while back and had forgotten to change the call in the repl which prints the result.
Also fixes a panic when exiting the repl, see 6afc82c8166f93e3222a2d93591bf58850a512bc for the fix and cause.
Fixes #255

fix: Fix issue #255

---

base/src/ast.rs
base/src/pos.rs
base/src/symbol.rs
base/src/types.rs
check/src/typecheck.rs
tests/vm.rs
vm/Cargo.toml
vm/src/api.rs
vm/src/compiler.rs
vm/src/core.rs
vm/src/lib.rs

Not yet working, just wanted to post for feedback. The current core::Expr type is really only removing/merging constructors and I have not taken how easy it is to optimize into account.
#107

refactor: Add a simpler intermediate represenentation

---

base/src/ast.rs
check/src/completion.rs
check/src/metadata.rs
check/src/rename.rs
check/src/typecheck.rs
parser/src/grammar.lalrpop
parser/src/lib.rs
parser/tests/basic.rs
src/main.rs
std/prelude.glu
tests/vm.rs
vm/Cargo.toml
vm/src/compiler.rs
vm/src/core.rs

Makes it possible to write gluon code where pattern matches are nested!
```f#
match { x = Some (Some 123) } with
| { x = Some None } -> 0
| { x = Some (Some x) } -> x
| { x = None } -> -1
```
To make this more efficient we could do some analysis to determine which variant to start generating match expressions on http://marijnhaverbeke.nl/hob/saga/pattern_matching.html.
Closes #1

feat: Implement nested pattern matching

---

vm/src/compiler.rs
vm/src/core/grammar.lalrpop
vm/src/core/mod.rs

This rewrites the entire pattern translation into the algorithm in [Derivation of a pattern matching compiler](http://homepages.inf.ed.ac.uk/wadler/papers/pattern/pattern.pdf) as well as [ 	The Implementation of Functional Programming Languages](https://www.microsoft.com/en-us/research/publication/the-implementation-of-functional-programming-languages/?from=http%3A%2F%2Fresearch.microsoft.com%2Fen-us%2Fum%2Fpeople%2Fsimonpj%2Fpapers%2Fslpj-book-1987%2Fstart.htm).
The implementation is currently a bit of a mess but it fixes some serious bugs which exist in the current implementation so I will do a cleanup later.

fix(compiler): Propagate catch-all patterns correctly during translation

---

TUTORIAL.md
base/src/ast.rs
base/src/symbol.rs
base/src/types.rs
check/src/completion.rs
check/src/kindcheck.rs
check/src/metadata.rs
check/src/rename.rs
check/src/typecheck.rs
check/tests/pass.rs
parser/src/grammar.lalrpop
parser/src/layout.rs
parser/src/lib.rs
parser/tests/basic.rs
std/prelude.glu
tests/vm.rs
vm/src/compiler.rs
vm/src/core/mod.rs

Tuples are currently syntax sugar over `{ _0: ..., _1: ..., ... }` which not only reduced the implementation complexity but also ensures that tuples can be projected from via `tuple._1`.

feat: Implement tuples

---

benches/check.rs
benches/function_call.rs
benches/parser.rs
examples/http.rs
rustfmt.toml
src/compiler_pipeline.rs
src/import.rs
src/io.rs
src/lib.rs
tests/api.rs
tests/compiletest.rs
tests/debug.rs
tests/error.rs
tests/http.rs
tests/io.rs
tests/main.rs
tests/metadata.rs
tests/parallel.rs
tests/regex_bind.rs
tests/stack_overflow.rs
tests/support/mod.rs
tests/tutorial.rs
tests/vm.rs

There does not seem to be a way to retain the behaviour of `where_trailing_comma = true` without having a traling comma on things like `Struct { field: 1, }` (single line) so I am just using the defaults again now.

style: Update rustfmt

---

base/src/kind.rs
base/src/lib.rs
base/src/types.rs
check/src/kindcheck.rs
check/src/lib.rs
check/src/rename.rs
check/src/substitution.rs
check/src/typecheck.rs
check/src/unify.rs
check/src/unify_type.rs
check/tests/row_polymorphism.rs
parser/src/grammar.lalrpop
parser/src/lib.rs

Adds `TypeCache` and `KindCache` which are used to share a single instance of various common types and kinds which will reduce memory usage and improve performance somewhat.
Further work on this could be to add a dynamic cache which would identify duplicate instance of  function or application types as well but this would necessitate a more complex refactor.
Part of #41

perf: Share type and kind instances instead of allocating new objects

---

base/src/error.rs
base/src/pos.rs
base/src/symbol.rs
base/src/types.rs
check/Cargo.toml
check/src/lib.rs
check/src/rename.rs
check/src/typecheck.rs
check/tests/fail.rs
check/tests/pass.rs
check/tests/support/mod.rs
vm/src/compiler.rs
vm/src/types.rs
vm/src/value.rs
vm/src/vm.rs

When creating a record the compiler attempts to look up a matching alias to simplify typechecking later on (since an alias is a smaller type than a record, most of the time). For the alias to unify correctly though its fields need to match exactly however whereas it used to only require a subset of them to match which is the case for looking up an alias from a field access or pattern match.
Fixes https://gitter.im/gluon-lang/gluon?at=59211caffa63ba2f76634737

fix(check): Require that an record alias matches exactly on record construction

---

check/src/completion.rs
check/src/metadata.rs
check/tests/completion.rs
check/tests/metadata.rs
check/tests/support/mod.rs
src/compiler_pipeline.rs
src/lib.rs
tests/vm.rs

Currently only works when completing on identifiers though in the future it should be possible to annotate types as well which would let
```
(f x).field
// ^ Should return documentation if `f x` returns a type that has documented `field`
```

feat(check): Allow retrieval of documentation through the completion interface

---

TUTORIAL.md
base/src/error.rs
check/src/typecheck.rs
check/src/unify.rs
check/src/unify_type.rs
check/tests/fail.rs
vm/src/vm.rs

I don't really have a good way to test that this fixes all cases but it should fix the majority of them.
Fixes #292

fix(check): Don't leak inference variables out to type errors

---

parser/Cargo.toml
parser/build.rs
vm/Cargo.toml

Fixes the petgrapth regression causing nightly to fail on travis

chore: Update lalrpop to 0.13.1 (with LALRPOP_LANE_TABLE=disabled)

---

repl/Cargo.toml
src/lib.rs
vm/Cargo.toml
vm/src/thread.rs

Examples added to run_expr(), define_global(), and get_global() docs
Closes #260

docs: Add examples and move tests into the documentation

---

base/src/resolve.rs
repl/src/repl.rs
src/compiler_pipeline.rs
src/lib.rs

Broken accidentally when let bindings without a body expression (`let x = 3`) were accepted in the repl
Fixes #334

fix(repl): Evaluate IO expressions automatically in the repl

---

examples/http.rs
vm/src/api/mod.rs
vm/src/api/typ.rs

(Ab)uses `Deseriailize` implementations to generate gluon types. Won't be able to generate types for nested enums but most everything else should work

feat: Allow gluon types to be generated from rust types

---

src/compiler_pipeline.rs
src/lib.rs

When compiled without 'serialization' feature, some 'unused import' warnings occur
(I used rustc 1.20.0).
This PR fixes them by adding `cfg` attributes.

Fix warnings raised when 'serialization' feature is not specified.

---

base/src/types/mod.rs
check/src/typecheck.rs
check/tests/fail.rs
check/tests/pass.rs
check/tests/support/mod.rs
check/tests/type_projection.rs

Since we want to provide the correct spans in the errors I had to hook into the ast type translation which was slightly awkward (need to clone `type_cache` to make lifetimes work).
```f#
type Test = Int
let module = { Test }
let x : module.Test = 1
x
```
Closes #192
Fixes #370

feat(check): Let type aliases be referred via projection

---

vm/src/gc.rs
vm/src/thread.rs
vm/src/vm.rs

Fixes a memory unsafety issue where a child thread could be freed if it only existed as a `RootedThread`

fix(vm): child_threads must be traversed for all threads

---

vm/src/array.rs
vm/src/value.rs

The use of `Void` in the `Array` type was meant to absolutely prevent the `Array` type from existing except behind a pointer which is invalid (except the empty array I guess) as the elements are stored inline behind the length field.
Unfortunately https://github.com/rust-lang/rust/pull/45225 made rustc think that fields of the `Array` type could not exist at all and placed fields of `Array` at the start of any struct containing them, causing any write to the `Array` to overwrite other fields.
Fixes #396

fix(vm): Don't let rustc think the Array type can't exist

---

README.md

I looked at gluon for the first time yesterday and I rearranged the sections in the readme a bit, based on my first impressions - 
* Moved examples up
* Fixed the repl usage snippet
* Added a section on testing

Rearranged sections for first time user

---

.gitignore
parser/build.rs
parser/src/grammar.rs
vm/build.rs
vm/src/core/grammar.rs

Should let gluon be ran under cargobomb https://github.com/rust-lang-nursery/crater/issues/157 but I think that regardless of that it is better to generate files outside of the source tree

chore: Write lalrpop files to OUT_DIR instead of the source tree

---

repl/src/repl.rs

When running completion in the repl I accidentally expanded macros twice which caused the implicit prelude to be inserted twice which caused an error in the implicit prelude (which is assumed to never happen). This caused a crash when trying to print the error since the error location is out of bounds (the crash happens when trying to complete any small enough input).
Fixes #408

fix(repl): Don't expand macros twice in repl completion

---

check/src/kindcheck.rs
check/src/lib.rs
check/src/metadata.rs
check/src/substitution.rs
check/src/typecheck.rs
check/src/unify.rs
check/src/unify_type.rs
check/tests/fail.rs
check/tests/forall.rs
check/tests/support/mod.rs
vm/src/thread.rs

The unification algorithm accidentally were to eager to instantiate
generic variables with fresh type variables which allowed programs to
pass typechecking even though they differed in the placement of
variables (see tests).
This fixes that by *ONLY* instantiating fresh typevariables during
subsumption (deduced from Purescript's implementation), otherwise we
only skolemize the variables (which ensures that different variables do
not unify with each other).
This would be enough to fix this, except the a quirk in how typechecking
proceeds throw a wrench into the mix. Consider the following example.
```f#
type Functor f = {
map : forall a b . (a -> b) -> f a -> f b,
}
let functor : Functor List =
let map = ...
{ map }
```
Since we want to preserve the alias during typechecking as long as …

Don't instantiate variables during unification inside aliases

---

completion/src/lib.rs
completion/tests/signature_help.rs
completion/tests/suggest.rs
completion/tests/support/mod.rs
std/parser.glu

This makes it possible to implement `textDocument/signatureHelp` for the
language server which displays information about the arguments of the
function call that is currently being written.

Provide signature help through completion

---

format/src/lib.rs
parser/Cargo.toml
parser/build.rs
parser/src/grammar.lalrpop
parser/src/layout.rs
parser/tests/error_handling.rs

This finally takes advantage of LALRPOPs lane table parser as the bugs in error recovery has now been fixed! I found some small behaviour changes but nothing really strange.
I will take another look at the extra CloseBlock token error before merging as well to see if that is expected.

Update LALRPOP to 0.14

---

.travis.yml
Cargo.toml
c-api/Cargo.toml
c-api/src/lib.rs
src/compiler_pipeline.rs
src/import.rs
src/lib.rs
vm/Cargo.toml
vm/src/api/mod.rs
vm/src/api/ser.rs
vm/src/api/typ.rs
vm/src/channel.rs
vm/src/compiler.rs
vm/src/core/interpreter.rs
vm/src/core/mod.rs
vm/src/core/optimize.rs
vm/src/gc.rs
vm/src/interner.rs
vm/src/lib.rs
vm/src/macros.rs
vm/src/serialization.rs
vm/src/source_map.rs
vm/src/stack.rs
vm/src/thread.rs
vm/src/types.rs
vm/src/value.rs
vm/src/vm.rs

Currently the `gluon_c-api` crate compiles down to ~3.5 MB (https://github.com/alexcrichton/wasm-gc does not make a dent) which may be a bit large but it could be interesting to make try_gluon run WASM instead of running the server side. If that change were made then it would be fairly simple to automatically provide errors as one writes code and things like that which would be cool! But it remains to be done at some later done.
Closes #424

feat: Let gluon compile to WASM

---

.gitignore
.travis.yml
CHANGELOG.md
Cargo.lock
Cross.toml
README.md
build.rs
repl/build.rs
scripts/before_deploy.sh
scripts/install_cross.sh
scripts/travis.sh

This currently produces x64 releases for Linux, OSX, and Windows (gnu) which should cover 99% of everyone which wants to use a prebuilt release.
Some potential additions could be to produce x86 releases, ARM and perhaps Windows msvc using Appveyor. See https://github.com/japaric/trust/blob/master/.travis.yml for a full(?) list.

Deploy gluon to github releases on git tags

---

completion/src/lib.rs
completion/tests/completion.rs
completion/tests/suggest.rs
completion/tests/support/mod.rs

There are some left that I'm not ready to do now:
```
warning: consider using `Option<T>` instead of `Option<Option<T>>` or a custom enum if you need to distinguish all 3 cases
--> completion/src/lib.rs:208:12
|
208 |     found: Option<Option<Match<'a>>>,
|            ^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: #[warn(option_option)] on by default
= help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.184/index.html#option_option
warning: this `match` has identical arm bodies
--> completion/src/lib.rs:735:19
|
735 |             }) => id.name.clone(),
|                   ^^^^^^^^^^^^^^^
|
= note: #[warn(match_same_arms)] on by default
note: same as this
--> completion/src/lib.rs:730:19
|
730 |             }) => id.name.clone(),
| …
```

Fix all clippy warnings in completion module

---

rustfmt.toml

I'm using `rustfmt 0.3.6-nightly (e0e3e22 2018-01-18)` and it emits a warning:
`Warning: Unknown configuration option error_on_line_overflow_comments`
I'm not sure what version you use, so feel free to close this as you see fit.

Use error_on_line_overflow option instead of error_on_line_overflow_comments

---

Cargo.lock
base/src/types/mod.rs
base/src/types/pretty_print.rs
base/tests/types.rs
check/Cargo.toml
check/src/lib.rs
check/src/metadata.rs
check/src/typecheck.rs
check/src/unify_type.rs
format/src/pretty_print.rs
repl/src/repl.rs

Instead of writing out the entire prelude record we will now get the below output. We could definitely still do better however (and the filtering is a bit imprecise right now since it applies to the entire type regardless of the nesting).
```
gluon (:h for help, :q to quit)
> let { Se = x } = import! std.prelude in x
<line>:Line: 1, Column: 5: Expected the following types to be equal
Expected:
{
...,
Semigroup = forall a . { ... },
Show = forall a . { ... },
make_Semigroup : forall a . std.prelude.Semigroup a -> { ... },
...
}
Found:
{
...,
Semigroup = forall a . { ... },
Show = forall a . { ... },
make_Semigroup : forall a . std.prelude.Semigroup a -> { ... },
| a
...
}
1 errors were found during unification:
The type `{
...,
Semigroup = forall a . { ... },
Show = forall a . { ... }, …
```

feat: Filter out unrelated fields in some type errors 

---

Cargo.lock
Cargo.toml
c-api/src/lib.rs
examples/http.rs
parser/Cargo.toml
repl/src/repl.rs
src/compiler_pipeline.rs
src/import.rs
src/io.rs
src/lib.rs
tests/de.rs
tests/io.rs
tests/support/mod.rs
tests/vm.rs
vm/Cargo.toml
vm/src/api/de.rs
vm/src/api/mod.rs
vm/src/api/ser.rs
vm/src/array.rs
vm/src/channel.rs
vm/src/debug.rs
vm/src/lazy.rs
vm/src/lib.rs
vm/src/primitives.rs
vm/src/reference.rs
vm/src/serialization.rs
vm/src/stack.rs
vm/src/thread.rs
vm/src/value.rs
vm/src/vm.rs

Start of #16 and #303. By restricting how `Value` can be used we have a
start towards making the vm actually memory safe. As a first step, this
prevents code outside of `gluon_vm` from accessing the `GcPtr`s inside
`Value`.

 refactor(vm): Make Value's internal strucuture private

---

.travis.yml
vm/src/array.rs
vm/src/serialization.rs
vm/src/value.rs

Working on getting WASM properly working and it appears that WASM acts as a 32-bit system. Since we never ran any tests on 32-bit that had been broken since forever.

fix(vm): Align garbage collected allocations correctly on 32-bit systems 

---

base/src/ast.rs
base/src/types/mod.rs
check/src/rename.rs
check/src/typecheck.rs
check/tests/forall.rs
check/tests/implicits.rs
completion/src/lib.rs
tests/vm.rs

Moves the renaming pass before metadata and typechecking so that typechecking can freely create symbols without worrying about renaming bulldozing it afterwards.

fix(check): Don't overwrite implicit variables in renaming

---

std/test.glu
tests/pass/alternative.glu
tests/pass/arithmetic.glu
tests/pass/channel.glu
tests/pass/deep_clone_userdata.glu
tests/pass/lazy.glu
tests/pass/lisp.glu
tests/pass/list.glu
tests/pass/map.glu
tests/pass/match_literal.glu
tests/pass/parser.glu
tests/pass/state.glu
tests/pass/stream.glu
tests/pass/string.glu
tests/pass/thread.glu
tests/pass/unwrap.glu
tests/pass/writer.glu

Closes #459
Wasn't able to convert `tests/pass/alternative.glu`, `tests/pass/map.glu`, `tests/pass/thread.glu`, so still use `old_assert_eq`
@Marwes here are my observations:
- errors need more love. I see you've already created #457. For example, it wasn't clear to me that I need to add `?` to import when using `*>` from `std.applicative`
- added some types to help the compiler; in particular in `tests` definitions, but it seems that to import `Test` from `std.test` is enough

Use assert_eq with implicit arguments in the test module

---

tests/pass/map.glu

`Eq (List a)` were not imported. Going to improve on the error message for (see #480) cc @zummenix

Fully use implicits in tests/pass/map.glu

---

repl/tests/rexpect.rs

A simple interface to ensure various lines are not forgetten to improve reliability of repl tests. Let's see how these fair, especially so more tests can be written!

Wrap repl tests in interface.

---

examples/marshalling.rs
vm/src/api/mod.rs
vm/src/thread.rs

This is a rather hacky solution as it needs to go through the
`Array/slice` marshalling. Ideally we should be able to serialize maps
through from Rust into any `Map`-like type on gluon's side automatically
but that requires the Rust -> Gluon FFI to understand implicits.

docs: Add an example on how to marshall map types

---

README.md

- fix broken embedded and tutorial links
- add link to gluon std docs
- add badges for crates, gluon book, and gluon std up top for easier access

readme link updates

---

Cargo.lock
check/Cargo.toml
check/src/implicits.rs
check/src/typecheck.rs
check/tests/implicits.rs
check/tests/pass.rs

Cuts the time of `cargo test --features test --test main` in about half.
This might cause some implicit bindings to fail to resolve if it the implicit type is hidden behind an alias, however that is not a huge problem + once type sealing gets added that will be semantically closer to this behaviour as well (but the issue with aliases should still be fixed).

perf(check): Partition the implicit bindings to reduce the search space

---

base/src/types/mod.rs
check/src/typecheck.rs
vm/src/compiler.rs
vm/src/core/mod.rs
vm/src/core/pretty.rs
vm/src/gc.rs
vm/src/thread.rs
vm/src/value.rs
vm/src/vm.rs

Removes ~80kb which isn't as much as I had hoped for, there are still
some redundant monomorphizations but those are trickier or have some
performance tradeoffs.
cc #345

refactor: Avoid unnecessary monomorphizations

---

codegen/src/getable.rs
codegen/src/pushable.rs
codegen/src/userdata.rs
codegen/src/vm_type.rs
codegen/tests/derive_getable.rs

When using the new derive macros, I noticed that tuple structs caused panics when deriving `Getable`, because that branch was not implemented. This fixes the problem and also adds `#[allow(unused_variables)]` to the generated code (occurs when using C-style enums, that do not use the `vm` parameter).

Fix derive Getable for tuple structs

---

.travis.yml
check/src/typecheck.rs
check/tests/pass.rs

As the repl invokes the typechecker without an expected type any array
in the tail expression would not get a type assigned to them.
Fixes #555

fix(repl): Don't panic on solo array literals

---

Cargo.toml
vm/src/api/de.rs
vm/src/api/ser.rs
vm/src/api/typ.rs

This makes clear which modules and examples require the `serialization` or `serde` feature flags, fixing non-obvious build errors (see #573). 
Closes #573

Document required serialization feature

---

book/src/marshalling-types.md

Since the impl of `Getable for *T where T: Userdata` conflicts with the
obvious impl here we must instead use a wrapper
Based on #586 
cc #592

feat(vm): Let Userdata be returned to Rust

---

tests/vm.rs

Use len instead of tag for verify record with 0 field.

Correct record test in vm

---

repl/src/main.rs

The `gluon` command provided by `gluon_repl` fails to print a trailing
newline after the usage string when no arguments are given, and it
fails to print a trailing newline after the error string when a file
provided as input cannot be found.  These missing newlines result in
unsightly output as the shell prints the `$PS1` without a preceding
line break.  The commits in this series address these two issues.

Fix missing newlines in gluon_repl command-line output

---

tests/api.rs
vm/src/api/mod.rs

The type of `Box<T>` is just `T` and for `Getable` we call `from_value` for `T` and box the result. This is useful because in recursive types in rust we often have to use Box in order for the type to have a finite size.
I *think* this should not cause any problems and with this implementation the user can just choose how to represent their gluon types in rust (i.e., with or without boxing), but feel free to correct me on that. Alternatively, one could implement a `Box`-like type in gluon and map those types, but I currently don't see a reason for that.
Unfortunately, `Pushable` cannot be implemented due to the conflicting implementation for `UserData` and I could not think of a workaround. Apparently, users can implement `UserData` (or any other trait for that matter) for …

Implement VmType and Getable for Box<T>

---

base/src/metadata.rs
check/src/implicits.rs
check/src/metadata.rs
check/tests/implicits.rs
check/tests/metadata.rs
completion/tests/completion.rs
format/tests/pretty_print.rs
tests/pass/derive.glu
tests/pass/json/de.glu
tests/pass/json/ser.glu
vm/src/derive.rs

This is important for generated code in `derive` so that it can write
its imports without worrying about the code outside of it.

feat: Allow implicit resolution if the same binding is included twice

---

repl/src/main.rs
repl/src/repl.glu
repl/src/repl.rs
repl/tests/rexpect.rs

The flakiness may be because some output matches the prompt that is used
so set a unique one.
cc #625

test: Try to make rexpect tests more reliable

---

README.md

Looks like the trailing slash is needed to resolve the try page.

Fix try link

---

codegen/src/vm_type.rs
codegen/tests/derive_vm_type.rs

Fixes `Type::variant` still being referred to as `Type::variants` in the `VmType` derive, which is currently broken for enums because of it.

Fix Type::variant call for VmType derive

---

base/src/lib.rs
repl/src/main.rs
repl/src/repl.glu
repl/src/repl.rs
src/io.rs
vm/src/value.rs
vm/src/vm.rs

Fixes #467.
In this PR, a general purpose global debugging status is added to GlobalVmState, and it is decided whether to print out the contents of functions based on the state.

Add global debugging status and decide whether to print out the contents of functions

---

check/src/typecheck.rs
parser/src/lib.rs
vm/src/api/de.rs
vm/src/gc.rs
vm/src/stack.rs

a simple refactor to use shorthand fields where possible

refactor(all): use shorthand fields

---

std/foldable.glu
std/parser.glu

Added `take` to `std.parser` exports and made second parameter of `std.foldable.elem` implicit

fix(std): fix a couple mistakes in a couple std modules

---

Cargo.toml
check/Cargo.toml
parser/Cargo.toml
parser/src/lib.rs
parser/tests/indentation.rs
parser/tests/stack_overflow.rs
parser/tests/support/mod.rs
vm/src/api/mod.rs
vm/src/compiler.rs
vm/src/core/interpreter.rs
vm/src/core/mod.rs
vm/src/core/optimize.rs

`cargo test --all --features test` is still necessary to run all tests but this will at least run most of them.

chore: Let cargo test work out of the box

---

base/src/scoped_map.rs
check/src/implicits.rs
check/src/substitution.rs
check/src/unify_type.rs
check/tests/implicits.rs
check/tests/support/mod.rs

There may be some quirks to workout but everything in the gluon repo
itself works fine. This avoids the huge error messages generated when
implicit resolution ends up in an infinite loop.

fix(check): Abort implicit checking immediately on infinite loops

---

README.md
base/src/ast.rs
book/src/syntax-and-semantics.md
check/src/rename.rs
check/src/typecheck.rs
check/tests/pass.rs
completion/src/lib.rs
examples/24.glu
examples/http/server.glu
examples/lisp/lisp.glu
examples/marshalling.rs
format/src/pretty_print.rs
parser/src/grammar.lalrpop
parser/src/layout.rs
parser/src/token.rs
parser/tests/basic.rs
repl/src/repl.glu
std/parser.glu
tests/io.rs
tests/pass/state.glu
tests/pass/thread.glu
vm/src/core/mod.rs

This adds the `seq EXPR1 in EXPR2` syntax which desugars to `flat_map (\_ -> EXPR2) EXPR1`. In the long run we should probably desugar this to
```
let x = lazy (\expr -> EXPR2)
flat_map x EXPR1
// or with **>> : [Applicative f] -> f a -> Lazy (f b) -> f b
// EXPR1 **>> x
```
cc #566

feat: Add seq expressions

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
base/Cargo.toml
base/src/lib.rs
c-api/Cargo.toml
c-api/src/lib.rs
check/Cargo.toml
check/src/lib.rs
check/src/typecheck.rs
check/src/unify_type.rs
check/tests/implicits.rs
codegen/Cargo.toml
completion/Cargo.toml
completion/src/lib.rs
doc/Cargo.toml
format/Cargo.toml
format/src/lib.rs
parser/Cargo.toml
parser/src/lib.rs
repl/Cargo.toml
scripts/version.sh
src/lib.rs
vm/Cargo.toml
vm/src/lib.rs

The previous, naive subsume_implicit function did not traverse the
functions simultaneously so the implicit arguments would be lost if the
left side had a `forall` at the top.
Fixes an issue found in #686
cc @Etherian

fix(check): Subsume implicit functions with forall correctly

---

scripts/install_mdbook.sh

mdbook does not provide binaries for osx (and we dont need to use mdbook on osx)

fix: Ignore mdbook for osx builds

---

Cargo.lock
base/src/types/mod.rs
base/src/types/pretty_print.rs
doc/Cargo.toml
doc/src/doc/module.html
doc/src/lib.rs
doc/tests/doc.rs
src/http.rs
src/io.rs
src/rand_bind.rs
src/regex_bind.rs
std/io.glu
vm/src/api/mac.rs
vm/src/api/record.rs
vm/src/channel.rs
vm/src/primitives.rs
vm/src/reference.rs
vm/src/vm.rs

Depends on https://github.com/deadlinks/cargo-deadlinks/pull/48
Fixes #693 
Fixes #694

fix(doc): Don't generate dead links in the documentation 

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
base/Cargo.toml
base/src/lib.rs
c-api/Cargo.toml
c-api/src/lib.rs
check/Cargo.toml
check/src/lib.rs
codegen/Cargo.toml
completion/Cargo.toml
completion/src/lib.rs
doc/Cargo.toml
format/Cargo.toml
format/src/lib.rs
parser/Cargo.toml
parser/src/lib.rs
repl/Cargo.toml
src/lib.rs
vm/Cargo.toml
vm/src/lib.rs

<a name="v0.11.2"></a>
* **doc:**  Don't display the full path to types in the documentation ([a669faaa](https://github.com/gluon-lang/gluon/commit/a669faaadadd388e23d36393204820d73316cbf5))
*   Ignore mdbook for osx builds ([7755967a](https://github.com/gluon-lang/gluon/commit/7755967ad5e3defb5a1d1b1c10ce920ec030556d))
* **check:**  The alias reduction stack must be cleared between unifying function arguments ([170072a4](https://github.com/gluon-lang/gluon/commit/170072a4734d4ec27c97c307aae7dc5b7d181dcc))
* **doc:**
*  Correct all the remaining links in docs ([494675fe](https://github.com/gluon-lang/gluon/commit/494675fe3dbfc229c795ed3b076ce0c87c7297a1))
*  Point breadcrumb links correctly ([2a9cca72](https://github.com/gluon-lang/gluon/commit/2a9cca7282a74bd13851a25f88f2b04d398f2dbe))
* …

Version 0.11.2

---

check/src/typecheck.rs
check/tests/fail.rs

Introduced when adding row polymorphism for variants which were need for
effects.
cc @tyler-conrad
Fixes #702
Fixes #703
Fixes #704
Fixes #705

fix(check): Don't lose type information in catch-all

---

check/src/implicits.rs
check/src/typecheck.rs
check/tests/implicits.rs
examples/http/main.rs
std/list.glu

Traverses records fully to bring their implicit instances in scope (`Monad -> Applicative -> Functor` etc)
Found in #686
cc @Etherian

fix(check): Bring nested implicit instances into scope

---

codegen/src/pushable.rs
vm/src/thread.rs

The generated code accounted for this but by moving it in we get a
simpler interface.
Fixes #719

fix(vm): Automatically remove the elements added to pushed data

---

Cargo.lock
tests/api.rs
tests/io.rs
tests/serialization.rs
vm/Cargo.toml
vm/src/api/mod.rs
vm/src/gc.rs
vm/src/serialization.rs
vm/src/stack.rs
vm/src/thread.rs
vm/src/value.rs
vm/src/vm.rs

Uses a very naive approach to determine if there still exists thread
references by scanning every thread. Could be faster but this fixes the
immediate issue.

fix: Ensure that threads are dropped when using child threads

---

std/array.glu
std/stream.glu

These are defined, but not exported.

feat(std): Export std.array.monoid and std.stream.uncons

---

codegen/src/attr.rs
codegen/src/lib.rs
codegen/src/userdata.rs
vm/src/api/mod.rs

If set and the deriving type implements `Clone`, the gluon type will be
cloneable.
Fixes #761

Add `#[gluon_userdata(clone)]` attribute

---

Cargo.lock
base/src/fixed.rs
check/Cargo.toml
check/src/implicits.rs
check/src/substitution.rs
check/src/typecheck.rs
check/src/unify_type.rs
check/tests/forall.rs
check/tests/implicits.rs
check/tests/pass.rs
check/tests/support/mod.rs
examples/24.rs

By checking the arguments before the `flat_map` call we can get more
information when we check it which prevents some type errors.
(https://xnning.github.io/papers/let-arguments-go-first.pdf motivates this
but I have yet to read it, will read it later to see if normal function
application should be changed as well)
Fixes #766

fix(check): Handle aliases better in `do`

---

repl/src/main.rs
src/import.rs
src/lib.rs

Adds a command-line switch `--no-std` to the standalone interpreter / REPL which causes it to ignore its internal standard library modules when searching for modules to import.
This should make less awkward to use the REPL to test changes to the standard library.
resolves #751

feat(repl): add a --no-std option to the standalone interpreter / REPL

---

.travis.yml
repl/Cargo.toml
repl/src/repl.rs
scripts/install_sccache.sh

fix: Don't depend on ansi_term in windows to make windows 7 work

---

repl/src/main.rs
repl/src/repl.rs

I forgot to handle the REPL case when adding `--no-std` to the interpreter/REPL. This PR rectifies that oversight.

fix(repl): make the REPL respect --no-std

---

repl/src/repl.rs
vm/src/primitives.rs

Now it prints a debug represnetation just like all the other `Show`
implementations. `string.from_char` and `string.append_char` are added
as replacements for turning a char to a readable string.
Fixes #784

fix: Make the behaviour consistent for `Show Char`

---

base/src/ast.rs
base/src/types/mod.rs
examples/http/server.glu
repl/src/repl.glu
src/compiler_pipeline.rs
src/import.rs
src/lib.rs
src/lift_io.rs
src/query.rs
std/effect/io.glu
std/effect/io/read.glu
std/effect/io/write.glu
std/http.glu
vm/src/core/interpreter.rs
vm/src/macros.rs

We do this by generating a module based on the types of `std.io` this
isn't perfect yet (see `catch` for instance) but it is a pretty good
approximation.

feat: Provide std.effect.io as a mirror of std.io

---

format/tests/pretty_print.rs
std/effect/error.glu
std/test.glu

Adds `some_or_throw` to `std.effect.error` and  `assert_ok`, `assert_err`, `assert_errorless`, and `assert_erroring` to `std.test`. I could also add `assert_lt`, `assert_lte`, `assert_gt`, and `assert_gte` if you like.

feat(std): add a few functions to std.test & std.effect.error

---

std/test.glu

I forgot to export the ordering assertion functions in my previous PR.

fix(std): export missing assertions in std.test

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
base/Cargo.toml
base/src/lib.rs
c-api/Cargo.toml
c-api/src/lib.rs
check/Cargo.toml
check/src/lib.rs
codegen/Cargo.toml
completion/Cargo.toml
completion/src/lib.rs
doc/Cargo.toml
format/Cargo.toml
format/src/lib.rs
parser/Cargo.toml
parser/src/lib.rs
repl/Cargo.toml
src/lib.rs
vm/Cargo.toml
vm/src/lib.rs

<a name="v0.13.0"></a>
This version mostly contains performance improvements, both during compilation and execution. The most notable of which is that gluon now has function inlining and constant folding. This lets simple calls like `1 + 2` be optimized into `3` at compile time and `x + 1` are now compiled as the primitive addition instruction instead of calling `std.int.num.(+)` first. Optimizations is enabled by default but can be disabled via the ´optimize` compiler setting. Together with some other optimizations, the factorial tests have received a 4x speedup. There are still more work to do on optimizing the virtual machine however as lua still comes out ahead by another 4x speedup.
Some breaking changes have occurred, the `gluon::Compiler` struct is no more. Instead, all it's …

Version 0.13.0

---

check/src/typecheck.rs
check/src/typecheck/error.rs
check/tests/fail.rs

... in a constructor
Fixes #807

fix(check): Reject programs which misspecifies the number of patterns

---

vm/src/api/mod.rs

This is required for cloning OwnedFunction<Hole>. Cloning is necessary, because calling a function requires &mut.

Added Clone trait for Hole

---

base/src/lib.rs
base/src/resolve.rs

fix: Accept filenames that start with `.`/`..` as modules

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
base/Cargo.toml
base/src/lib.rs
c-api/Cargo.toml
c-api/src/lib.rs
check/Cargo.toml
check/src/implicits.rs
check/src/lib.rs
codegen/Cargo.toml
completion/Cargo.toml
completion/src/lib.rs
doc/Cargo.toml
format/Cargo.toml
format/src/lib.rs
parser/Cargo.toml
parser/src/lib.rs
repl/Cargo.toml
repl/src/main.rs
scripts/release.sh
scripts/version.sh
src/lib.rs
vm/Cargo.toml
vm/src/lib.rs

*   Rework how hanging lambda/parens are handled ([732f09f](732f09f))
*   Accept filenames that start with `.`/`..` as modules ([01e450b](01e450b))
*   Don't deadlock when collecting and cloning a thread concurrently ([5886f59](5886f59))
* **check:**  Reject programs which misspecifies the number of patterns ([248387d](248387d), closes [#807](#807))
* **doc:**  Correct the style.css path ([4e629ab](4e629ab))
* **format:**  Improve tuple multiline formatting ([5122fe3](5122fe3))
*   Add AstClone to clone arena allocated ASTs ([3ee7bd2](3ee7bd2))
*   Compile modules in parallel using salsa-async ([e0ab181](e0ab181))
*   Compile modules in parallel ([57fca16](57fca16))
*   Add Function::call_any ([2c06104](2c06104))
*   Export Array from the prelude ([16eb345](16eb345))
*   Allow …

Version 0.14.0

---

tests/serialization.rs
vm/src/primitives.rs

The name generated for the function must match the path that they exist
atm otherwise they can't be looked up during deserialization.
cc @omegablitz

fix: Allow bitoperations to be deserialized

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
base/Cargo.toml
base/src/lib.rs
c-api/Cargo.toml
c-api/src/lib.rs
check/Cargo.toml
check/src/lib.rs
codegen/Cargo.toml
completion/Cargo.toml
completion/src/lib.rs
doc/Cargo.toml
format/Cargo.toml
format/src/lib.rs
parser/Cargo.toml
parser/src/lib.rs
repl/Cargo.toml
src/lib.rs
vm/Cargo.toml
vm/src/lib.rs

<a name="v0.15.0"></a>
*   Allow bitoperations to be deserialized ([ed36ed9c](https://github.com/gluon-lang/gluon/commit/ed36ed9ccc5e423fd872994ffb52edda97c8965d))
*   Strategically inline comment productions ([78e733e7](https://github.com/gluon-lang/gluon/commit/78e733e701abe71ee10048b3de3b550bed927f43))
*   Shrink the metadata stored in the AST ([842c1080](https://github.com/gluon-lang/gluon/commit/842c1080bb73a7509384064e07a671b2c0f11fb6))
*   Use T::Generics in AliasData ([4cb575fa](https://github.com/gluon-lang/gluon/commit/4cb575fac5356bbc9a018eb6779c209a3473d3b6))
*   Shrink the symbol type in the parser ([a8fc8f39](https://github.com/gluon-lang/gluon/commit/a8fc8f39556a2997e359288ec37dfd9bd0932d7d))
*   Accept multiple lines on incomplete repl input …

Version 0.15.0

---

std/json/de.glu
std/map.glu
tests/api.rs
vm/src/api/mod.rs
vm/src/thread.rs

Also move the insert_string hack into std.map so std.json.de does not
need to be imported
Fixes #847

fix: Handle errors when pushing a BTreeMap

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
base/Cargo.toml
base/src/lib.rs
c-api/Cargo.toml
c-api/src/lib.rs
check/Cargo.toml
check/src/lib.rs
codegen/Cargo.toml
completion/Cargo.toml
completion/src/lib.rs
doc/Cargo.toml
format/Cargo.toml
format/src/lib.rs
parser/Cargo.toml
parser/src/lib.rs
repl/Cargo.toml
src/lib.rs
vm/Cargo.toml
vm/src/lib.rs

<a name="v0.16.0"></a>
*   Make tokio an optional dependency ([c3450a99](https://github.com/gluon-lang/gluon/commit/c3450a99656f2c6298d7b937d976ac5d0e96f6c2), closes [#843](https://github.com/gluon-lang/gluon/issues/843))
*   Update to codespan_reporting 0.9 ([a6f214ce](https://github.com/gluon-lang/gluon/commit/a6f214ce120c34f37d5b2169dba593f576f24265))
*   Handle errors when pushing a BTreeMap ([bd8ad34f](https://github.com/gluon-lang/gluon/commit/bd8ad34fbf294729442c0c8d0e8983903b59cbdf), closes [#847](https://github.com/gluon-lang/gluon/issues/847))
*   Convert rust tuples such that they can be used polymorphically ([6c4d5731](https://github.com/gluon-lang/gluon/commit/6c4d5731cefff867f468c2982eb55df6cf69aa8f), closes [#848](https://github.com/gluon-lang/gluon/issues/848))

Version 0.16.0

---

base/src/types/mod.rs
base/tests/types.rs

fix: Keep type field arguments on the same line as the name

---

std/applicative.glu

fix missing code markup in applicative doc

---

vm/src/primitives.rs

For `Int` adds
- `rem`
- `checked_rem`
- `wrapping_rem`
- `overflowing_rem`
- `rem_euclid`
- `checked_rem_euclid`
- `wrapping_rem_euclid`
- `overflowing_rem_euclid`
For `Float` adds
- `rem`
- `rem_euclid`

feat(std): Add 'remainder' functions for Int and Float

---

tests/main.rs

test: Extract doc tests defined in record fields

---

std/test.glu

Adds `assert_some` and `assert_none`. I guess I forgot them when adding `assert_ok` and `assert_err`.

feat(std): add Option assertions to std.test

---

.travis.yml
base/src/types/mod.rs
completion/src/lib.rs
tests/compile-fail/run_expr_str_ref.rs
vm/src/api/function.rs

These cannot be called from the gluon side, instead a one argument
function that takes `()` should be used.
bors r+
Fixes #873

fix: Prevent zero-argument functions from being created in Rust

---

codegen/src/shared.rs

Currently, `gluon_codegen` unconditionall inserts a comma after the
user-provided `where` clause. However, the `where` clause may already
have a trailing comma, which will result in an unparsable `TokenStream`
being generated.
The `AliasRef` struct would be affected by this bug, but a rustc bug
causes the exact parsed `TokenStream` to be lost in some cases
(see https://github.com/rust-lang/rust/issues/43081) - in this case, due
to the presence of `#[cfg_attr]`.
When PR https://github.com/rust-lang/rust/pull/76130 is merged, the
exact parsed `TokenStream` will be passed to proc-macros in more cases,
exposing this bug.

Don't insert a duplicate trailing comma in `gluon_codegen`

---

parser/src/token.rs
parser/tests/basic.rs
parser/tests/support/mod.rs

fix: Recognize raw string literals without any `#`

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
base/Cargo.toml
base/src/lib.rs
c-api/Cargo.toml
c-api/src/lib.rs
check/Cargo.toml
check/src/lib.rs
codegen/Cargo.toml
completion/Cargo.toml
completion/src/lib.rs
doc/Cargo.toml
format/Cargo.toml
format/src/lib.rs
parser/Cargo.toml
parser/src/lib.rs
repl/Cargo.toml
src/lib.rs
vm/Cargo.toml
vm/src/lib.rs

<a name="v0.17.2"></a>
*   Allow the http module to be used without a tcp listener ([c45353d2](https://github.com/gluon-lang/gluon/commit/c45353d2ceb10d98dbeca7e7dce1f658b875eb3a))
*   Format seq expressions without seq ([5c0cec2d](https://github.com/gluon-lang/gluon/commit/5c0cec2d29a0580a8e171e040f13427b282c4c1f))
*   Compile block expressions as monadic sequences ([bce59737](https://github.com/gluon-lang/gluon/commit/bce5973719cdb24849671f5b11e980e5d9cefc31), closes [#884](https://github.com/gluon-lang/gluon/issues/884))
* **std:**
*  add Option assertions to std.test ([28e5053f](https://github.com/gluon-lang/gluon/commit/28e5053f1e56f7304d8b94eead3174ccfa4077c6))
*  add modulo functions to int and float ([92f188ab](https://github.com/gluon-lang/gluon/commit/92f188ab24b599d0d0ef004c996f …

Version 0.17.2

---

README.md
src/import.rs
src/lift_io.rs
vm/src/macros.rs

feat: Allow macros to refer to symbols in scope at the expansion site

---

base/src/scoped_map.rs
check/src/typecheck.rs
check/tests/pass.rs

 fix: Don't refine already refined skolems

---

CHANGELOG.md
CONTRIBUTING.md
Cargo.lock
Cargo.toml
README.md
base/Cargo.toml
base/src/lib.rs
c-api/Cargo.toml
c-api/src/lib.rs
check/Cargo.toml
check/src/lib.rs
codegen/Cargo.toml
completion/Cargo.toml
completion/src/lib.rs
doc/Cargo.toml
format/Cargo.toml
format/src/lib.rs
parser/Cargo.toml
parser/src/lib.rs
repl/Cargo.toml
src/lib.rs
vm/Cargo.toml
vm/src/lib.rs

<a name="v0.18.0"></a>
*   Avoid recreating the vm for each formatted file ([0335733](0335733))
*   Make channels and reference require IO ([c904189](c904189), breaks [#](https://github.com/gluon-lang/gluon/issues/))
*   Make channels and reference require IO ([c904189](c904189), breaks [#](https://github.com/gluon-lang/gluon/issues/))
*   Allow specifying type signatures in do bindings ([fac08dc](fac08dc))
*   Allow macros to refer to symbols in scope at the expansion site ([1a5489c](1a5489c), closes [#895](#895))
*   Allow the http module to be used without a tcp listener ([c45353d](c45353d))
*   Format seq expressions without seq ([5c0cec2](5c0cec2))
*   Compile block expressions as monadic sequences ([bce5973](bce5973), closes [#884](#884))
* **std:**
*  add Option assertions to …

Version 0.18.0
