std/state.glu
std/test.glu
std/writer.glu

Implement Applicative and Functor for State and Writer

---

base/src/instantiate.rs
base/src/scoped_map.rs
base/src/symbol.rs
check/src/completion.rs
check/src/rename.rs
check/src/typecheck.rs
check/src/unify_type.rs
check/tests/typecheck.rs
vm/src/compiler.rs
vm/src/vm.rs

Also fixes some fallout which was masked by fixing the double listing

fix(check): Fix errors uncovered from using (->) partially applied

---

base/src/instantiate.rs
base/src/scoped_map.rs
base/src/symbol.rs
check/src/completion.rs
check/src/rename.rs
check/src/typecheck.rs
check/src/unify_type.rs
check/tests/typecheck.rs
parser/src/lib.rs
std/prelude.glu
vm/src/compiler.rs
vm/src/vm.rs

Add Category interface and piping operators

---

base/src/instantiate.rs
base/src/types.rs
base/tests/types.rs
check/src/kindcheck.rs
check/src/typecheck.rs
check/src/unify_type.rs
check/tests/functions.rs
check/tests/typecheck.rs
parser/src/lib.rs
parser/tests/basic.rs
vm/src/api.rs
vm/src/channel.rs
vm/src/compiler.rs
vm/src/lazy.rs
vm/src/reference.rs
vm/src/vm.rs

Remove Type::App variant

---

base/src/ast.rs
base/src/instantiate.rs
base/src/types.rs
check/src/kindcheck.rs
check/src/typecheck.rs
check/src/unify_type.rs
check/tests/typecheck.rs
vm/src/compiler.rs

Remove Type::Function

---

.travis.yml
README.md

Adds a gitter badge to the readme and travis integration for gitter.

chore: Add a gitter chatroom

---

base/Cargo.toml
base/src/ast.rs
base/src/instantiate.rs
base/src/lib.rs
base/src/types.rs
check/src/rename.rs
check/src/typecheck.rs
check/src/unify_type.rs
check/tests/fail.rs
check/tests/pass.rs
vm/src/thread.rs

Still struggling to get the right semantics of when to bail out in the unifier. Currently I am getting either bad error messages or errors in typechecking. Making a PR to show WIP though.

Handle infinite recursive types

---

base/src/types.rs
base/tests/types.rs
check/src/kindcheck.rs
check/src/typecheck.rs
check/tests/functions.rs
check/tests/pass.rs
parser/src/lib.rs
src/repl.rs
vm/src/types.rs
vm/src/vm.rs

Rename (*) to type

---

base/src/ast.rs
base/src/error.rs
base/src/lib.rs
base/src/pos.rs
check/src/completion.rs
check/src/rename.rs
check/src/typecheck.rs
check/tests/completion.rs
check/tests/fail.rs
check/tests/pass.rs
parser/src/lib.rs
parser/tests/basic.rs
src/import.rs
vm/src/value.rs

This should make it easier to implement #108 in a type-driven way.

Use typed byte and character positions

---

base/src/ast.rs
base/src/pos.rs
check/src/completion.rs
check/src/metadata.rs
check/src/rename.rs
check/src/typecheck.rs
check/tests/completion.rs
check/tests/pass.rs
check/tests/support/mod.rs
parser/Cargo.toml
parser/src/lexer.rs
parser/src/lib.rs
parser/tests/basic.rs
parser/tests/indentation.rs
parser/tests/stack_overflow.rs
src/import.rs
src/lib.rs
src/repl.rs
vm/src/compiler.rs
vm/src/macros.rs

Continuation of #116 
Closes #121

Use spans instead of single locations in AST

---

base/src/ast.rs
base/src/error.rs
base/src/lib.rs
base/src/pos.rs
base/src/source.rs
check/src/completion.rs
check/src/rename.rs
check/src/typecheck.rs
check/tests/completion.rs
check/tests/pass.rs
check/tests/support/mod.rs
parser/src/lexer.rs
parser/src/lib.rs
parser/tests/basic.rs
parser/tests/indentation.rs
src/lib.rs
src/repl.rs

Use byte offsets instead of locations in AST

---

vm/src/api.rs
vm/src/channel.rs
vm/src/primitives.rs
vm/src/reference.rs

refactor: Rename MaybeError to RuntimeResult

---

base/src/ast.rs
base/src/instantiate.rs
base/src/types.rs
base/tests/types.rs
c-api/src/lib.rs
check/src/completion.rs
check/src/kindcheck.rs
check/src/lib.rs
check/src/metadata.rs
check/src/rename.rs
check/src/typecheck.rs
check/src/unify_type.rs
check/tests/pass.rs
check/tests/support/mod.rs
parser/src/lib.rs
parser/tests/basic.rs
src/import.rs
vm/src/api.rs
vm/src/compiler.rs
vm/src/macros.rs
vm/src/thread.rs
vm/src/types.rs
vm/src/value.rs
vm/src/vm.rs

Just a bunch of stuff I found while muddling around on the parser. I also reordered the type module somewhat because I kept getting lost due to things not being grouped together correctly.

Identifier cleanups 

---

TUTORIAL.md
src/io.rs
std/repl.glu
std/string.glu
tests/vm.rs
vm/src/lib.rs
vm/src/primitives.rs
vm/src/thread.rs

See individual commits for all the fixes.

fix: Various fixes to the repl

---

base/src/error.rs
base/src/pos.rs
base/src/source.rs
check/tests/completion.rs
check/tests/pass.rs
check/tests/support/mod.rs
parser/src/lexer.rs
parser/tests/basic.rs
parser/tests/indentation.rs
src/repl.rs
tests/error.rs
tests/support/mod.rs

Improving the the implementation of this by moving to 0-based indexing. Closes #153

Line and column numbering improvements

---

TUTORIAL.md
build.rs
c-api/src/lib.rs
check/src/typecheck.rs
src/io.rs
src/lib.rs
tests/io.rs
tests/main.rs
tests/support/mod.rs
tests/tutorial.rs
tests/vm.rs
vm/src/api.rs
vm/src/thread.rs
vm/src/value.rs

feat(vm): Fix and cleanup the run_expr method

---

vm/src/thread.rs

This is added to work in a similiar way to the debug hook in Lua but is currently very basic. In its current form it is still usable as a means to prevent infinite loops by adding a timeout which is checked in the hook

feat(vm): Add a hook function which is executed on every closure call

---

CHANGELOG.md
Cargo.toml
README.md
base/Cargo.toml
c-api/Cargo.toml
check/Cargo.toml
parser/Cargo.toml
src/lib.rs
vm/Cargo.toml
vm/src/debug.rs
vm/src/lib.rs
vm/src/primitives.rs

There are two small changes in this PR as well which I didn't bother making a separate PR for. I think they should be pretty uncontroversial though. If you find any changes I missed for the changelog please let me know and I will add them.

feat: Release version 0.2.0

---

CHANGELOG.md
CONTRIBUTING.md
Cargo.toml
README.md
TUTORIAL.md
base/Cargo.toml
check/Cargo.toml
parser/Cargo.toml
src/lib.rs
vm/Cargo.toml

Fixes #178 
@Marwes and please don't forget to create a new gitter channel for this 😅

Update URLs to point to new organization

---

base/src/error.rs
base/src/source.rs

Extracted from #182 to first be able to use the language server with 0.2 letting #182 wait until they have been tested with the language server.

feat: Tweaks to enable the language server to work with 0.2

---

base/src/symbol.rs
base/src/types.rs
src/compiler_pipeline.rs
src/import.rs
src/io.rs
src/lib.rs
src/main.rs
tests/vm.rs
vm/src/compiler.rs
vm/src/lib.rs
vm/src/source_map.rs
vm/src/stack.rs
vm/src/value.rs
vm/src/vm.rs

Resurrected another old branch which adds source maps. Currently this always creates the map which may not be desirable but it should be very low overhead and optional creation may be added later. Going to experiment with this a bit in the language server so I may need to tweak the interface of this before we can merge this.

feat: Source map

---

.travis.yml

Can't really test if this works unfortunately :/

fix: Specify the release executable relative the build directory

---

base/src/error.rs
base/src/instantiate.rs
base/src/types.rs
check/src/kindcheck.rs
check/src/rename.rs
check/src/typecheck.rs
check/src/unify_type.rs
parser/src/lexer.rs
parser/src/lib.rs
rustfmt.toml
src/compiler_pipeline.rs
src/import.rs
src/io.rs
src/lib.rs
src/main.rs
src/repl.rs
tests/main.rs
tests/parallel.rs
vm/src/api.rs
vm/src/channel.rs
vm/src/compiler.rs
vm/src/debug.rs
vm/src/interner.rs
vm/src/lazy.rs
vm/src/primitives.rs
vm/src/reference.rs
vm/src/stack.rs
vm/src/thread.rs
vm/src/value.rs
vm/src/vm.rs

Use try shorthand

---

parser/src/infix.rs
parser/src/lib.rs

Return spanned errors from infix reparser

---

.travis.yml

Remove documentation upload from .travis.yml

---

base/src/kind.rs
check/src/kindcheck.rs
check/src/typecheck.rs
check/tests/fail.rs
check/tests/pass.rs
parser/src/grammar.lalrpop
parser/tests/support/mod.rs
std/prelude.glu

Implement explicit kinds on type alias parameters

---

base/src/ast.rs
base/src/resolve.rs
base/src/types.rs
base/tests/types.rs
check/src/kindcheck.rs
check/src/typecheck.rs
check/src/unify_type.rs
check/tests/completion.rs
check/tests/pass.rs
check/tests/row_polymorphism.rs
parser/tests/basic.rs
parser/tests/support/mod.rs
src/lib.rs
vm/src/api.rs

Splitting out some stylistic changes from #215 into this PR so that it is easier to review.

Assorted cleanups to alias handling

---

vm/src/api.rs
vm/src/channel.rs
vm/src/value.rs

feat: Add a macro for describing gluon record patterns

---

base/src/ast.rs
check/src/typecheck.rs

fix(check): Fill in the unified types of function arguments properly

---

base/src/types.rs
vm/Cargo.toml
vm/src/lib.rs
vm/src/value.rs

Split out from #213 for easier reviewing.

feat(vm): Add a pretty printer on vm values

---

base/src/ast.rs
base/src/error.rs
base/src/fnv.rs
base/src/resolve.rs
base/src/source.rs
base/src/types.rs
check/src/kindcheck.rs
check/src/lib.rs
check/src/typecheck.rs
check/src/unify_type.rs
parser/src/infix.rs
parser/src/lib.rs
parser/src/token.rs
src/import.rs
src/io.rs
src/lib.rs
vm/src/api.rs
vm/src/gc.rs
vm/src/thread.rs

This does not fix all clippy warnings since there seems to be a problem with stack overflows
https://github.com/Manishearth/rust-clippy/issues/1244

style: Run clippy on the project

---

parser/src/lib.rs
src/main.rs

I also fixed a spelling error in an error message.

style: using clap_app macro for readability

---

.travis.yml
Cargo.toml
check/src/unify_type.rs
repl/Cargo.toml
repl/src/lib.rs
repl/src/main.rs
repl/src/repl.rs
src/import.rs
src/lib.rs

This should allow --no-default-features to work with the gluon crate
Fixed #267

fix(repl): Move the repl to its own crate

---

.travis.yml
appveyor.yml
repl/Cargo.toml
repl/src/repl.rs
vm/build.rs

chore: Try to get travis releases up and running

---

Cargo.toml
check/src/typecheck.rs
check/tests/pass.rs
examples/http.glu
examples/http.rs
examples/http_server.glu
examples/http_types.glu
src/lib.rs
std/http.glu
std/string.glu
tests/api.rs
tests/http.rs
vm/src/api.rs
vm/src/primitives.rs
vm/src/thread.rs

Threw together a super simple http server example for fun. I'd like to extend it a bit more and add comments but I think this could make a decent example (though it is an example that requires some pretty hefty dependencies unfortunately).

docs: Add an example of a http server

---

parser/src/grammar.lalrpop
parser/src/lib.rs
parser/tests/error_handling.rs
repl/src/lib.rs

Made some small usuability fixes

---

README.md
parser/src/grammar.lalrpop
parser/src/lib.rs
repl/src/main.rs
repl/src/repl.rs
src/compiler_pipeline.rs
src/lib.rs
std/repl.glu
vm/src/api.rs
vm/src/dynamic.rs
vm/src/lib.rs
vm/src/thread.rs

There may be some bugs but given how useful this is I think it's still worthwhile, it is unlikely to break any existing functionality as well.
Fixes #271

feat(repl): Allow binding variables in the repl for later use

---

parser/src/token.rs

https://gitter.im/gluon-lang/gluon?at=5942a9f5e531dbc905e799da

feat(parser): (Re-)add negative numbers to the language

---

base/src/ast.rs
base/src/pos.rs
check/src/completion.rs
check/src/metadata.rs
check/src/rename.rs
check/src/typecheck.rs
check/tests/completion.rs
parser/Cargo.toml
parser/src/grammar.lalrpop
parser/src/token.rs
parser/tests/error_handling.rs
vm/src/core/mod.rs

This makes gluon provide auto completion for variants that are in scope when completing in a match pattern (see tests).

feat(check): Auto complete pattern matches

---

.travis.yml
tests/de.rs
vm/src/api/de.rs
vm/src/api/mod.rs
vm/src/array.rs
vm/src/channel.rs
vm/src/compiler.rs
vm/src/primitives.rs

Various fixes

---

TUTORIAL.md
base/src/pretty_print.rs
base/src/source.rs
parser/Cargo.toml
parser/src/infix.rs
parser/src/layout.rs
parser/src/lib.rs
parser/tests/pretty_print.rs
vm/src/core/mod.rs

Partial fix for #307 . Still work to do to handle comments properly but this should be a nice improvement

Format fixes

---

base/src/pretty_print.rs
base/src/source.rs
parser/tests/pretty_print.rs

Comments inside tuples and records should now be kept!
cc #307

feat: Vastly improve when comments are kept during formatting

---

base/src/ast.rs
base/src/kind.rs
base/src/lib.rs
base/src/resolve.rs
base/src/serialization.rs
base/src/symbol.rs
base/src/types.rs
check/Cargo.toml
check/src/completion.rs
check/src/kindcheck.rs
check/src/lib.rs
check/src/substitution.rs
check/src/typecheck.rs
check/src/unify.rs
check/src/unify_type.rs
check/tests/completion.rs
check/tests/fail.rs
check/tests/pass.rs
check/tests/support/mod.rs
tests/main.rs

First draft of a rewrite which fixes #161

feat: Rewrite the overload algorithm to fix soundness issues

---

base/src/source.rs
check/src/completion.rs
check/tests/completion.rs

Provide more information for the language server

---

README.md
TUTORIAL.md

docs: Update the documentation links to point to docs.rs

---

CHANGELOG.md
Cargo.toml
README.md
base/Cargo.toml
base/src/lib.rs
c-api/Cargo.toml
c-api/src/lib.rs
check/Cargo.toml
check/src/lib.rs
completion/Cargo.toml
completion/src/lib.rs
format/Cargo.toml
format/src/lib.rs
parser/Cargo.toml
parser/src/lib.rs
repl/Cargo.toml
src/lib.rs
tests/array.rs
tests/debug.rs
tests/io.rs
tests/pattern_match.rs
tests/support/mod.rs
tests/vm.rs
vm/Cargo.toml

Rushing out cada3a1 to unbreak the implicit prelude.

Version 0.6.2

---

CONTRIBUTING.md

docs: Update Contributing.md#Testing

---

vm/src/api/mod.rs
vm/src/core/interpreter.rs
vm/src/core/mod.rs

@brendanzab Attempted to explain the pattern translator as best I can. Not sure how much it helps with #342 but given the complexity the docs should be there regardless.

docs: Explain the pattern match translator 

---

README.md

Related https://github.com/salpalvv/vim-gluon/pull/1
Closes #381

Expand the vim support in the readme

---

parser/src/token.rs

#385, This supports only integer hex literals.

parser: Adjust parser to accept integer hex literals

---

base/src/ast.rs
base/src/kind.rs
base/src/source.rs
base/src/symbol.rs
base/src/types/mod.rs
check/src/kindcheck.rs
check/src/substitution.rs
check/src/typecheck.rs
check/src/unify.rs
check/src/unify_type.rs
check/tests/fail.rs
completion/Cargo.toml
completion/src/lib.rs
completion/tests/completion.rs
scripts/travis.sh
src/import.rs
vm/src/api/de.rs

feat: Provide completion inside types

---

vm/src/value.rs

fix(repl): Print out Char as the "character" in thre repl

---

base/src/ast.rs
base/src/pos.rs
parser/src/token.rs
parser/tests/basic.rs
parser/tests/error_handling.rs
parser/tests/support/mod.rs
parser/tests/types.rs

- add additional visitor methods in MutVisitor
- clean span values for testing purpuses
- fix all tests
Closes #394 
P.S: Sorry for the giant commit, I was working on this during the week and completely messed up git history.

Add PartialEq for spans

---

base/src/ast.rs
base/src/symbol.rs
base/src/types/pretty_print.rs
check/src/typecheck.rs
check/tests/support/mod.rs
completion/Cargo.toml
completion/src/lib.rs
completion/tests/completion.rs
completion/tests/support/mod.rs
parser/src/grammar.lalrpop
parser/src/layout.rs
parser/tests/error_handling.rs
repl/src/repl.rs
src/compiler_pipeline.rs
src/import.rs
src/lib.rs
tests/serialization.rs
tests/vm.rs
vm/src/core/interpreter.rs
vm/src/core/mod.rs
vm/src/core/optimize.rs
vm/src/primitives.rs
vm/src/thread.rs
vm/src/types.rs
vm/src/value.rs
vm/src/vm.rs

Provide better completion when writing imports

---

c-api/src/lib.rs
examples/http.rs
examples/marshalling.rs
repl/src/repl.rs
src/io.rs
src/lib.rs
tests/compile-fail/get-reference.rs
tests/de.rs
vm/src/api/de.rs
vm/src/api/mod.rs
vm/src/channel.rs
vm/src/lazy.rs
vm/src/primitives.rs
vm/src/thread.rs

All tests pass. Let me know if I need to add additional checks.
Closes #229

Change Getable::from_value to return a value instead of Option

---

base/Cargo.toml
base/src/ast.rs
base/src/lib.rs
check/src/metadata.rs
check/src/rename.rs
check/src/typecheck.rs
completion/src/lib.rs
format/src/pretty_print.rs
parser/Cargo.toml
parser/src/grammar.lalrpop
parser/src/lib.rs
repl/src/repl.rs
tests/pass/match_literal.glu
tests/pattern_match.rs
vm/src/api/mod.rs
vm/src/api/ser.rs
vm/src/api/typ.rs
vm/src/compiler.rs
vm/src/core/grammar.lalrpop
vm/src/core/interpreter.rs
vm/src/core/mod.rs
vm/src/core/optimize.rs
vm/src/primitives.rs

Allow pattern matching on literals

---

vm/src/core/mod.rs

- move the `check_translation` function up and use it in all tests.
- consistent formatting for hanging `";` and `"#;`

Use check_translation in all tests

---

.travis.yml
check/src/unify_type.rs
check/tests/fail.rs

fix(check): Don't print type mismatches betwen EmptyRow 

---

check/src/typecheck.rs
check/tests/fail.rs

fix: Don't panic if let bindings has more arguments than declared type

---

TUTORIAL.md
base/src/ast.rs
check/src/rename.rs
check/src/typecheck.rs
check/tests/implicits.rs
completion/src/lib.rs
format/src/pretty_print.rs
parser/src/grammar.lalrpop
parser/tests/support/mod.rs
tests/pattern_match.rs
tests/vm.rs
vm/src/core/mod.rs
vm/src/gc.rs

Found in the tutorial after re-enabling skeptic testing.

Fix issues that were found from enabling skeptic tests

---

README.md

I noticed that it has more commits.

Change vim-gluon link to point to gluon-lang/vim-gluon

---

Cargo.lock
repl/Cargo.toml
repl/tests/tests.rs

Add basic REPL tests using rexpect.

---

.travis.yml
repl/tests/rexpect.rs

Seeing some problems with rexpect as well as some timeouts (due to unknown reasons). Hopefully this should fix them.

Test flakiness

---

.travis.yml

The error only shows up after merging so.

chore: Fix the before_deploy travis script

---

src/import.rs
src/lib.rs
std/byte.glu
tests/pass/arithmetic.glu
tests/pass/char.glu
vm/src/primitives.rs

Add additional type conversion functions

---

README.md
examples/24.glu
examples/24.rs
repl/build.rs
scripts/travis.sh

Will at least fix one issue with 24.glu, need to check if #500 works after this is merged.

 Ensure the 24.glu example is tested 

---

.travis.yml
Cargo.lock
Cargo.toml
base/src/ast.rs
base/src/error.rs
base/src/kind.rs
base/src/lib.rs
base/src/pos.rs
base/src/symbol.rs
base/src/types/mod.rs
benches/parser.rs
benches/precompiled.rs
check/Cargo.toml
check/src/implicits.rs
check/src/lib.rs
check/src/metadata.rs
check/src/rename.rs
check/src/typecheck.rs
check/tests/fail.rs
check/tests/implicits.rs
parser/Cargo.toml
parser/src/grammar.lalrpop
parser/src/infix.rs
parser/src/lib.rs
parser/src/token.rs
scripts/travis.sh
vm/src/api/typ.rs
vm/src/vm.rs

Example https://github.com/gluon-lang/gluon/pull/518/files#diff-b03a06301460c980427e57cc5fa8c527R451
Fixes #480

feat: Improve the error message for unresolved implicits 

---

.travis.yml
bors.toml

chore: Use bors to test PRs

---

base/src/error.rs
check/src/typecheck.rs
check/src/unify_type.rs
check/tests/fail.rs

Does not display the information if an explicit, implicit argument is
passed but that is much rarer and tricker to get right
Fixes #508

feat(check): Improve error message for applying to many arguments

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
base/Cargo.toml
base/src/lib.rs
c-api/Cargo.toml
c-api/src/lib.rs
check/Cargo.toml
check/src/lib.rs
codegen/Cargo.toml
completion/Cargo.toml
completion/src/lib.rs
doc/Cargo.toml
format/Cargo.toml
format/src/lib.rs
parser/Cargo.toml
parser/src/lib.rs
repl/Cargo.toml
scripts/release.sh
src/lib.rs
vm/Cargo.toml

Got to many changes included in the previous PR (#545 ) so I merged that beforehand.

Really release 0.8

---

base/src/resolve.rs
check/src/typecheck.rs
check/tests/pass.rs
check/tests/support/mod.rs

fix(check): Don't shadow more general variant constructors

---

CHANGELOG.md
Cargo.toml
README.md
base/Cargo.toml
base/src/lib.rs
c-api/Cargo.toml
c-api/src/lib.rs
check/Cargo.toml
check/src/lib.rs
codegen/Cargo.toml
completion/Cargo.toml
completion/src/lib.rs
doc/Cargo.toml
format/Cargo.toml
format/src/lib.rs
parser/Cargo.toml
parser/src/lib.rs
repl/Cargo.toml
scripts/version.sh
src/lib.rs
vm/Cargo.toml

Fixes a few bugs, one of which should travis produce release artifacts again (which are missing for 0.8).
See the changelog for full details.

Version 0.8.1

---

Cargo.lock
Cargo.toml
base/src/kind.rs
base/src/types/mod.rs
base/src/types/pretty_print.rs
base/tests/types.rs
check/src/substitution.rs
check/src/typecheck.rs
check/src/unify.rs
doc/Cargo.toml
doc/build.rs
doc/src/doc/index.html
doc/src/doc/module.html
doc/src/lib.rs
doc/tests/doc.rs
format/src/lib.rs
format/src/pretty_print.rs
vm/src/api/typ.rs

feat(doc): Make all types link to their definition

---

c-api/src/lib.rs
codegen/src/getable.rs
examples/http/main.rs
examples/marshalling.rs
src/lib.rs
tests/support/mod.rs
vm/src/api/de.rs
vm/src/api/mod.rs
vm/src/serialization.rs
vm/src/thread.rs
vm/src/vm.rs

BREAKING CHANGE
Add the `'value` lifetime

feat(vm): Let `Getable` return types bound to the lifetime of Variants

---

repl/tests/rexpect.rs
src/compiler_pipeline.rs
src/io.rs
tests/vm.rs
vm/src/api/function.rs
vm/src/stack.rs
vm/src/thread.rs

Probably more instances where this is wrong but I need to do a larger
refactor to catch them all

 fix(vm): Restore the vm to a valid state after error has occured

---

vm/src/api/function.rs

Derive clone and debug for function

---

src/lib.rs

Fix tutorial link

---

book/src/standard-types-and-functions.md
src/import.rs
src/lib.rs
std/json/de.glu
std/json/ser.glu
std/json/value.glu
std/random.glu

Print a hint/warning towards necessary feature gates when importing modules

---

base/src/ast.rs
base/src/error.rs
base/src/lib.rs
base/src/merge.rs
base/src/metadata.rs
base/src/pos.rs
base/src/resolve.rs
base/src/serialization.rs
base/src/source.rs
base/src/symbol.rs
base/src/types/mod.rs
base/src/types/pretty_print.rs
vm/src/serialization.rs

Further fixes are blocked on
https://github.com/rust-lang-nursery/rust-clippy/issues/2831

style: Fix clippy warnings in gluon_base

---

check/src/typecheck.rs
check/tests/fail.rs

fix(check): Correct the order of expected and actual hints

---

src/import.rs
vm/src/lib.rs

feat(vm): Allow module loaders to contain state

---

book/src/syntax-and-semantics.md
check/src/typecheck.rs
check/tests/pass.rs
tests/vm.rs
vm/src/core/mod.rs

fix: Use the field order of the base record in record updates

---

Cargo.lock
doc/Cargo.toml
doc/src/doc/module.html
doc/src/lib.rs
doc/src/main.rs
doc/tests/doc.rs
std.glu

feat(doc): Link to the github source 

---

.travis.yml

Haven't been used in ages
bors r+

chore: Don't deploy github pages anymore

---

src/lib.rs
src/std_lib.rs
src/std_lib/env.rs
src/std_lib/http.rs
src/std_lib/io.rs
src/std_lib/process.rs
src/std_lib/random.rs
src/std_lib/regex.rs
std/env.glu

Add std.env 

---

base/src/types/mod.rs
codegen/src/getable.rs
codegen/tests/full.rs

fix: Handle newtypes with a public field

---

vm/src/vm.rs

Fix f32 impl of VmType

---

README.md

doc: Fix link to the embedding api

---

base/src/serialization.rs
base/src/symbol.rs
build.rs
check/src/metadata.rs
check/src/typecheck/error.rs
check/tests/metadata.rs
parser/src/infix.rs
src/std_lib/env.rs
src/std_lib/io.rs
src/std_lib/random.rs
src/std_lib/regex.rs
vm/src/core/mod.rs
vm/src/debug.rs
vm/src/lazy.rs
vm/src/primitives.rs
vm/src/reference.rs
vm/src/serialization.rs
vm/src/value.rs

fix(check): Propagate metadata through parens 

---

README.md
vm/src/thread.rs

Found while checking the http implementation.
cc #746

fix(vm): Check if a collection is needed when creating a child thread

---

tests/pattern_match.rs
vm/src/core/mod.rs

fix(compiler): Don't panic when matching a tuple against an alias

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
base/Cargo.toml
base/src/lib.rs
c-api/Cargo.toml
c-api/src/lib.rs
check/Cargo.toml
check/src/lib.rs
codegen/Cargo.toml
completion/Cargo.toml
completion/src/lib.rs
doc/Cargo.toml
format/Cargo.toml
format/src/lib.rs
parser/Cargo.toml
parser/src/lib.rs
repl/Cargo.toml
src/lib.rs
vm/Cargo.toml
vm/src/lib.rs

<a name="v0.12.0"></a>
*   Remove Userdata and Trace impls for RwLock and Mutex ([e90f02b5](https://github.com/gluon-lang/gluon/commit/e90f02b56afd40e00b6e9fba58dd5421cd91a6d2))
*   Add missing negate function from the prelude ([0091f475](https://github.com/gluon-lang/gluon/commit/0091f475355b2bc1562dc6e257826ff71e7faf7c))
*   Refer to registered types by their full name ([a2daace6](https://github.com/gluon-lang/gluon/commit/a2daace6e914157391b8453c97ddd675b86a7165), breaks [#](https://github.com/gluon-lang/gluon/issues/))
*   Handle newtypes with a public field ([d1fef968](https://github.com/gluon-lang/gluon/commit/d1fef9688a3c8d379df0837ee18a4ff8f79c91ae), closes [#713](https://github.com/gluon-lang/gluon/issues/713))
*   Don't ICE on unapplied, aliased constructors …

Version 0.12.0

---

Cargo.lock
base/src/ast.rs
benches/check.rs
check/src/rename.rs
check/src/typecheck.rs
check/tests/support/mod.rs
completion/tests/support/mod.rs
src/compiler_pipeline.rs
src/import.rs
src/lib.rs
vm/Cargo.toml
vm/src/serialization.rs
vm/src/thread.rs

feat: Use line/column numbers in lambda names

---

examples/marshalling.rs

doc: Show how to marshal a recursive gluon value

---

Cargo.lock
codegen/src/getable.rs
codegen/src/pushable.rs
codegen/src/vm_type.rs
codegen/tests/derive_getable.rs
codegen/tests/derive_pushable.rs
codegen/tests/derive_vm_type.rs
tests/main.rs
vm/src/api/de.rs
vm/src/api/ser.rs
vm/src/api/typ.rs

feat(codegen): Map Rust's struct enums to records in Gluon. 

---

codegen/src/userdata.rs
examples/marshalling.rs
parser/src/grammar.lalrpop
tests/api.rs

fix: Add tests and fix the regression with clone_userdata

---

codegen/src/trace.rs
codegen/src/userdata.rs
examples/lisp/lisp.glu
repl/src/main.rs
src/lib.rs
std/effect/st.glu
std/effect/st/string.glu
std/foldable.glu
vm/src/api/mod.rs
vm/src/channel.rs
vm/src/core/interpreter.rs
vm/src/gc.rs
vm/src/primitives.rs

This can be used to efficiently construct strings

feat: Add a mutable string type to the ST monad

---

check/src/implicits.rs
check/src/typecheck.rs
check/tests/implicits.rs
tests/pass/arithmetic.glu

fix: Don't leak implicit bindings into adjacent scopes

---

codegen/src/trace.rs
doc/src/lib.rs
scripts/publish.sh
src/query.rs
vm/src/api/function.rs
vm/src/api/mod.rs
vm/src/api/opaque.rs
vm/src/api/scoped.rs
vm/src/array.rs
vm/src/channel.rs
vm/src/gc.rs
vm/src/gc/mutex.rs
vm/src/interner.rs
vm/src/lazy.rs
vm/src/macros.rs
vm/src/reference.rs
vm/src/serialization.rs
vm/src/stack.rs
vm/src/thread.rs
vm/src/value.rs
vm/src/vm.rs

 fix: Don't deadlock when collecting and cloning a thread concurrently

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
base/Cargo.toml
base/src/lib.rs
c-api/Cargo.toml
c-api/src/lib.rs
check/Cargo.toml
check/src/lib.rs
codegen/Cargo.toml
completion/Cargo.toml
completion/src/lib.rs
doc/Cargo.toml
format/Cargo.toml
format/src/lib.rs
parser/Cargo.toml
parser/src/lib.rs
repl/Cargo.toml
scripts/publish.sh
src/lib.rs
vm/Cargo.toml
vm/src/lib.rs

<a name="v0.13.1"></a>
*   Don't deadlock when collecting and cloning a thread concurrently ([d736895](d736895))
* **doc:**  Correct the style.css path ([2cee5cf](2cee5cf))

Version 0.13.1

---

.travis.yml
scripts/before_deploy.sh
scripts/install_sccache.sh
scripts/publish.sh

chore: Don't put put artifacts in the build directory on publish

---

base/src/types/mod.rs
check/src/typecheck.rs
check/tests/fail.rs
src/lift_io.rs

Improve some error messages

---

Cargo.lock
Cargo.toml
parser/Cargo.toml
parser/benches/parser.rs
scripts/travis.sh

refactor: Move the parser benchmark to gluon_parser

---

README.md
vm/src/api/function.rs

Allows a function to be called if the number of arguments is only known
at runtime.

feat: Add Function::call_any

---

README.md
codegen/tests/derive_getable.rs
examples/marshalling.rs
src/lib.rs
std/array.glu
std/json/de.glu
std/prelude.glu
vm/Cargo.toml
vm/src/api/json.rs
vm/src/api/mod.rs
vm/src/primitives.rs

feat: Allow serde_json::Value to be marshalled to std.json.Value

---

Cargo.toml

Cargo.toml: add keywords

---

Cargo.lock
parser/src/grammar.lalrpop
parser/src/layout.rs
parser/src/lib.rs
parser/src/token.rs
parser/tests/error_handling.rs
repl/Cargo.toml
repl/src/repl.rs

Might be a better heuristic than just detecting blocks that could not be closed but it is a start.
cc @codesections
bors r+
Closes #830

feat: Accept multiple lines on incomplete repl input

---

format/tests/pretty_print.rs

Was presumably fixed in #696
Closes #793

test: Add tests for #793

---

Cargo.lock
build.rs
doc/src/lib.rs
repl/src/repl.rs
src/compiler_pipeline.rs
src/import.rs
src/lib.rs
src/query.rs
tests/vm.rs
vm/Cargo.toml
vm/src/api/ser.rs
vm/src/compiler.rs
vm/src/core/mod.rs
vm/src/lib.rs
vm/src/primitives.rs
vm/src/thread.rs
vm/src/vm.rs

One less thing that is untracked by salsa.

refactor: Store ExternLoaders in salsa

---

scripts/publish.sh

Publish gluon codegen

---

tests/api.rs
vm/src/api/mod.rs

fix: Convert rust tuples such that they can be used polymorphically

---

Cargo.lock
Cargo.toml
src/import.rs
src/lib.rs
src/query.rs
tests/fail/cyclic_dependency.glu
tests/fail/unwrap.glu
tests/main.rs

fix: Gracefully error on concurrently loaded cyclic modules

---

Cargo.lock
Cargo.toml
base/src/resolve.rs
repl/src/repl.rs
src/compiler_pipeline.rs
src/import.rs
src/lib.rs
src/query.rs
vm/src/macros.rs

Now based on trait objects, we end up with a lot less duplicated code.
Smaller binaries and faster compiles!

feat: Update salsa

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
base/Cargo.toml
base/src/lib.rs
c-api/Cargo.toml
c-api/src/lib.rs
check/Cargo.toml
check/src/lib.rs
codegen/Cargo.toml
completion/Cargo.toml
completion/src/lib.rs
doc/Cargo.toml
format/Cargo.toml
format/src/lib.rs
parser/Cargo.toml
parser/src/grammar.lalrpop
parser/src/lib.rs
repl/Cargo.toml
src/lib.rs
vm/Cargo.toml
vm/src/core/mod.rs
vm/src/lib.rs

Release 0.17.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
base/Cargo.toml
base/src/lib.rs
c-api/Cargo.toml
c-api/src/lib.rs
check/Cargo.toml
check/src/lib.rs
codegen/Cargo.toml
completion/Cargo.toml
completion/src/lib.rs
doc/Cargo.toml
format/Cargo.toml
format/src/lib.rs
parser/Cargo.toml
parser/src/lib.rs
repl/Cargo.toml
src/lib.rs
vm/Cargo.toml
vm/src/lib.rs

<a name="v0.17.1"></a>
*   Disable inlining until it can be made sound ([97b63c42](https://github.com/gluon-lang/gluon/commit/97b63c42717d5080dd4ccfe5f7df26479124ef0f))
*   Inline functions that are re-exports ([bcf87838](https://github.com/gluon-lang/gluon/commit/bcf878385c09291a4b9256688a6f76818039a888))
* **opt:**
*  Constant fold through simple matches ([360c9d0a](https://github.com/gluon-lang/gluon/commit/360c9d0a93ffc6b624821d925303fb0441407850))
*  Inline functions with impure arguments ([669f959d](https://github.com/gluon-lang/gluon/commit/669f959d6b21c4d8792d6d13ce109166f1d212f1))

Version 0.17.1

---

base/src/pos.rs
base/src/symbol.rs
base/src/types/mod.rs

Fixes https://github.com/gluon-lang/gluon_language-server/issues/40

fix: Give tuple fields a span

---

book/src/marshalling-types.md
examples/marshalling.rs

@crides does this explain it?
Closes #882

doc: Explain the vm_type attribute better

---

scripts/publish.sh
scripts/sync_publish.sh
src/std_lib/http.rs

feat: Allow the http module to be used without a tcp listener

---

.github/workflows/rust.yml
src/query.rs

Seems to be broken now and I don't think I use it.
Closes #938

chore: Remove cross from CI

---

.github/workflows/rust.yml
tests/api.rs

The ICE has been fixed so we can restore stable compilation again.
https://github.com/rust-lang/rust/issues/112832
Closes #951

chore: Compile on stable rust on CI again
